apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: configure-pks
spec:
  taskRef:
    name: configure-opsman-pks
  podTemplate:
    volumes:
      - name: pks-config-scripts
        configMap:
          name: opsman-config-pks-script
      - name: pks-config-volume
        configMap:
          name: opsman-pks-config
      - name: pks-config-certs
        secret:
          secretName: opsman-pks-cert