apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeAddress
metadata:
  name: {{ include "opsman.fullname" . }}-pks-api
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  addressType: EXTERNAL
  description: PKS API Load Balancer
  location: us-central1
