apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: {{ include "opsman.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: '{{ .Values.certManagerEmail }}'
    privateKeySecretRef:
      name: {{ include "opsman.fullname" . }}-cert-mgr
    http01: {}
    dns01:
      providers:
      - name: prod-clouddns
        clouddns:
          project: {{ .Values.projectID }}
          serviceAccountSecretRef:
            name: google-credentials
            key: key.json
