apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opsman.fullname" . }}-iaas-config
  namespace: tekton-install-pks
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  iaas.yaml: |-
    properties-configuration:
      iaas_configuration:
        project: {{ .Values.opsman.config.projectID }}
        default_deployment_tag: {{ include "opsman.fullname" . }}
        auth_json: SECRET
      director_configuration:
        ntp_servers_string: metadata.google.internal
        resurrector_enabled: true
        post_deploy_enabled: true
        database_type: internal
        blobstore_type: local
      security_configuration:
        trusted_certificates: ""
        vm_password_type: generate
    az-configuration:
      - name: us-central1-a
      - name: us-central1-b
      - name: us-central1-c
    networks-configuration:
      icmp_checks_enabled: false
      networks:
      - name: {{ include "opsman.fullname" . }}-pks-infrastructure
        service_network: false
        subnets:
        - iaas_identifier: {{ include "opsman.fullname" . }}-pks-network/{{ include "opsman.fullname" . }}-pks-infrastructure/us-central1
          cidr: 192.168.101.0/26
          reserved_ip_ranges: 192.168.101.1-192.168.101.9
          dns: 169.254.169.254
          gateway: 192.168.101.1
          availability_zone_names: [us-central1-a,us-central1-b,us-central1-c]
      - name: {{ include "opsman.fullname" . }}-pks-subnet
        service_network: false
        subnets:
        - iaas_identifier: {{ include "opsman.fullname" . }}-pks-network/{{ include "opsman.fullname" . }}-pks-subnet/us-central1
          cidr: 192.168.16.0/26
          reserved_ip_ranges: 192.168.16.1-192.168.16.9
          dns: 169.254.169.254
          gateway: 192.168.16.1
          availability_zone_names: [us-central1-a,us-central1-b,us-central1-c]
      - name: {{ include "opsman.fullname" . }}-pks-services
        service_network: true
        subnets:
        - iaas_identifier: {{ include "opsman.fullname" . }}-pks-network/{{ include "opsman.fullname" . }}-pks-services/us-central1
          cidr: 192.168.20.0/22
          reserved_ip_ranges: 192.168.20.1-192.168.20.9
          dns: 169.254.169.254
          gateway: 192.168.20.1
          availability_zone_names: [us-central1-a,us-central1-b,us-central1-c]
    network-assignment:
      network:
        name: {{ include "opsman.fullname" . }}-pks-infrastructure
      singleton_availability_zone:
        name: us-central1-a
    resource-configuration:
      director:
        instance_type:
          id: large.disk
        internet_connected: true
      compilation:
        instance_type:
          id: large.cpu
        internet_connected: true