apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opsman.fullname" . }}-pks-config
  namespace: tekton-install-pks
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  pks.yaml: |-
    product-name: pivotal-container-service
    product-properties:
      .pivotal-container-service.pks_tls:
        value:
          cert_pem: ""
          private_key_pem: ""
      .properties.cloud_provider:
        selected_option: gcp
        value: GCP
      .properties.cloud_provider.gcp.master_service_account:
        value: {{ include "opsman.fullname" . }}-pks-master@{{ .Values.projectID }}.iam.gserviceaccount.com
      .properties.cloud_provider.gcp.network:
        value: {{ include "opsman.fullname" . }}-pks-network
      .properties.cloud_provider.gcp.project_id:
        value: {{ .Values.projectID }}
      .properties.cloud_provider.gcp.worker_service_account:
        value: {{ include "opsman.fullname" . }}-pks-worker@{{ .Values.projectID }}.iam.gserviceaccount.com
      .properties.log_sink_resources_deploy:
        value: true
      .properties.metric_sink_resources_deploy:
        value: true
      .properties.network_selector:
        selected_option: flannel
        value: flannel
      .properties.network_selector.flannel.pod_network_cidr:
        value: 10.200.0.0/16
      .properties.network_selector.flannel.service_cluster_cidr:
        value: 10.100.200.0/24
      .properties.node_exporter_deploy:
        value: false
      .properties.oidc_selector:
        selected_option: enabled
        value: enabled
      .properties.oidc_selector.enabled.groups_claim:
        value: roles
      .properties.oidc_selector.enabled.groups_prefix:
        value: 'oidc:'
      .properties.oidc_selector.enabled.username_claim:
        value: user_name
      .properties.oidc_selector.enabled.username_prefix:
        value: 'oidc:'
      .properties.pks-vrli:
        selected_option: disabled
        value: disabled
      .properties.pks-vrops:
        selected_option: disabled
        value: disabled
      .properties.pks_api_hostname:
        value: pks.{{ .Values.dns.zone }}
      .properties.plan1_selector:
        selected_option: active
        value: Plan Active
      .properties.plan1_selector.active.addons_spec:
        value: {{ .Values.pks.plans.addons | quote }}
      .properties.plan1_selector.active.allow_privileged_containers:
        value: false
      .properties.plan1_selector.active.description:
        value: basic kubernetes cluster.  does not allow privileged, but does not enforce
          psps
      .properties.plan1_selector.active.errand_vm_type:
        value: large.cpu
      .properties.plan1_selector.active.kubelet_drain_delete_local_data:
        value: true
      .properties.plan1_selector.active.kubelet_drain_force:
        value: true
      .properties.plan1_selector.active.kubelet_drain_force_node:
        value: true
      .properties.plan1_selector.active.kubelet_drain_grace_period:
        value: 10
      .properties.plan1_selector.active.kubelet_drain_ignore_daemonsets:
        value: true
      .properties.plan1_selector.active.kubelet_drain_timeout:
        value: 10
      .properties.plan1_selector.active.master_az_placement:
        value:
        - {{ index .Values.google.zones 1 }}
      .properties.plan1_selector.active.master_instances:
        value: 1
      .properties.plan1_selector.active.master_persistent_disk_type:
        value: "20480"
      .properties.plan1_selector.active.master_vm_type:
        value: medium.disk
      .properties.plan1_selector.active.max_worker_instances:
        value: 50
      .properties.plan1_selector.active.name:
        value: basic
      .properties.plan1_selector.active.worker_az_placement:
        value:
        {{- range .Values.google.zones }}
          - {{ . }}
        {{- end }}

      .properties.plan1_selector.active.worker_instances:
        value: 1
      .properties.plan1_selector.active.worker_persistent_disk_type:
        value: "102400"
      .properties.plan1_selector.active.worker_vm_type:
        value: large.disk
      .properties.plan2_selector:
        selected_option: active
        value: Plan Active
      .properties.plan2_selector.active.addons_spec:
        value: {{ .Values.pks.plans.addons | quote }}
      .properties.plan2_selector.active.admission_plugins:
        value:
        - pod_security_policy
      .properties.plan2_selector.active.allow_privileged_containers:
        value: true
      .properties.plan2_selector.active.description:
        value: This plan creates a cluster that supports privileged mode, but also enforces
          PSPs
      .properties.plan2_selector.active.errand_vm_type:
        value: large.cpu
      .properties.plan2_selector.active.kubelet_drain_delete_local_data:
        value: true
      .properties.plan2_selector.active.kubelet_drain_force:
        value: true
      .properties.plan2_selector.active.kubelet_drain_force_node:
        value: true
      .properties.plan2_selector.active.kubelet_drain_grace_period:
        value: 10
      .properties.plan2_selector.active.kubelet_drain_ignore_daemonsets:
        value: true
      .properties.plan2_selector.active.kubelet_drain_timeout:
        value: 10
      .properties.plan2_selector.active.master_az_placement:
        value:
        - {{ index .Values.google.zones 1 }}
      .properties.plan2_selector.active.master_instances:
        value: 1
      .properties.plan2_selector.active.master_persistent_disk_type:
        value: "20480"
      .properties.plan2_selector.active.master_vm_type:
        value: medium.disk
      .properties.plan2_selector.active.max_worker_instances:
        value: 50
      .properties.plan2_selector.active.name:
        value: privileged
      .properties.plan2_selector.active.worker_az_placement:
        value:
        {{- range .Values.google.zones }}
          - {{ . }}
        {{- end }}
      .properties.plan2_selector.active.worker_instances:
        value: 1
      .properties.plan2_selector.active.worker_persistent_disk_type:
        value: "102400"
      .properties.plan2_selector.active.worker_vm_type:
        value: large.disk
      .properties.plan3_selector:
        selected_option: active
        value: Plan Active
      .properties.plan3_selector.active.addons_spec:
        value: {{ .Values.pks.plans.addons | quote }}
      .properties.plan3_selector.active.allow_privileged_containers:
        value: false
      .properties.plan3_selector.active.description:
        value: this plan is for workshop clusters
      .properties.plan3_selector.active.errand_vm_type:
        value: large.cpu
      .properties.plan3_selector.active.kubelet_drain_delete_local_data:
        value: true
      .properties.plan3_selector.active.kubelet_drain_force:
        value: true
      .properties.plan3_selector.active.kubelet_drain_force_node:
        value: true
      .properties.plan3_selector.active.kubelet_drain_grace_period:
        value: 10
      .properties.plan3_selector.active.kubelet_drain_ignore_daemonsets:
        value: true
      .properties.plan3_selector.active.kubelet_drain_timeout:
        value: 10
      .properties.plan3_selector.active.master_az_placement:
        value:
        {{- range .Values.google.zones }}
          - {{ . }}
        {{- end }}
      .properties.plan3_selector.active.master_instances:
        value: 1
      .properties.plan3_selector.active.master_persistent_disk_type:
        value: "20480"
      .properties.plan3_selector.active.master_vm_type:
        value: medium.disk
      .properties.plan3_selector.active.max_worker_instances:
        value: 50
      .properties.plan3_selector.active.name:
        value: workshop
      .properties.plan3_selector.active.worker_az_placement:
        value:
        {{- range .Values.google.zones }}
          - {{ . }}
        {{- end }}
      .properties.plan3_selector.active.worker_instances:
        value: 3
      .properties.plan3_selector.active.worker_persistent_disk_type:
        value: "204800"
      .properties.plan3_selector.active.worker_vm_type:
        value: xlarge.disk
      .properties.plan4_selector:
        selected_option: inactive
        value: Plan Inactive
      .properties.plan5_selector:
        selected_option: inactive
        value: Plan Inactive
      .properties.plan6_selector:
        selected_option: inactive
        value: Plan Inactive
      .properties.plan7_selector:
        selected_option: inactive
        value: Plan Inactive
      .properties.plan8_selector:
        selected_option: inactive
        value: Plan Inactive
      .properties.plan9_selector:
        selected_option: inactive
        value: Plan Inactive
      .properties.plan10_selector:
        selected_option: inactive
        value: Plan Inactive
      .properties.plan11_selector:
        selected_option: inactive
        value: Plan Inactive
      .properties.plan12_selector:
        selected_option: inactive
        value: Plan Inactive
      .properties.plan13_selector:
        selected_option: inactive
        value: Plan Inactive
      .properties.proxy_selector:
        selected_option: disabled
        value: Disabled
      .properties.syslog_selector:
        selected_option: disabled
        value: disabled
      .properties.telemetry_installation_purpose_selector:
        selected_option: demo_or_poc
        value: demo_or_poc
      .properties.telemetry_selector:
        selected_option: enabled
        value: enabled
      .properties.telemetry_selector.enabled.billing_polling_interval:
        value: 60
      .properties.telemetry_selector.enabled.environment_provider:
        value: none
      .properties.telemetry_selector.enabled.telemetry_polling_interval:
        value: 600
      .properties.telemetry_selector.enabled.telemetry_url:
        value: https://vcsa.vmware.com/ph
      .properties.uaa:
        selected_option: internal
        value: internal
      .properties.uaa_pks_cli_access_token_lifetime:
        value: 2600
      .properties.uaa_pks_cli_refresh_token_lifetime:
        value: 2160000
      .properties.uaa_pks_cluster_client_access_token_lifetime:
        value: 2600
      .properties.uaa_pks_cluster_client_refresh_token_lifetime:
        value: 21600
      .properties.vm_extensions:
        value:
        - public_ip
      .properties.wavefront:
        selected_option: disabled
        value: disabled
      .properties.worker_max_in_flight:
        value: 5
    network-properties:
      network:
        name: {{ include "opsman.fullname" . }}-pks-subnet
      other_availability_zones:
      {{- range .Values.google.zones }}
      - name: {{ . }}
      {{- end }}
      service_network:
        name: {{ include "opsman.fullname" . }}-pks-services
      singleton_availability_zone:
        name: {{ index .Values.google.zones 1 }}
    resource-config:
      pivotal-container-service:
        instances: automatic
        persistent_disk:
          size_mb: automatic
        instance_type:
          id: large
        internet_connected: true
        elb_names:
        - tcp:{{ include "opsman.fullname" . }}-pks-api
        max_in_flight: 4
    errand-config:
      delete-all-clusters:
        pre-delete-state: true
      pks-nsx-t-precheck:
        post-deploy-state: false
      smoke-tests:
        post-deploy-state: false
      upgrade-all-service-instances:
        post-deploy-state: false
      wavefront-alert-creation:
        post-deploy-state: false
      wavefront-alert-deletion:
        pre-delete-state: false
