{{- if .Values.database.enabled }}
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: {{ include "opsman.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  region: us-central1
  databaseVersion: MYSQL_5_7
  settings:
    tier: db-n1-standard-1
---
apiVersion: sql.cnrm.cloud.google.com/v1alpha3
kind: SQLDatabase
metadata:
  name: {{ include "opsman.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  charset: utf8mb4
  collation: utf8mb4_bin
  instanceRef:
    name: {{ include "opsman.fullname" . }}
---
apiVersion: sql.cnrm.cloud.google.com/v1alpha3
kind: SQLUser
metadata:
  name: {{ include "opsman.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  instanceRef:
    name: {{ include "opsman.fullname" . }}
  host: "{{ .Values.database.host }}"
  password: "{{ .Values.database.password }}"
{{- end }}