{{- if .Values.createIAM }}
# above is to disable doing IAM for now until I figure out the bug
# until then IAM is created via README.
apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMServiceAccount
metadata:
  name: "{{ include "opsman.fullname" . }}-pks-master"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  displayName: {{ include "opsman.fullname" . }} master acount
---
apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMServiceAccount
metadata:
  name: "{{ include "opsman.fullname" . }}-pks-worker"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  displayName: {{ include "opsman.fullname" . }} worker acount
---
apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMPolicy
metadata:
  name: "{{ include "opsman.fullname" . }}-pks-master"
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1alpha1
    kind: IAMServiceAccount
    name: "{{ include "opsman.fullname" . }}-pks-master"
  bindings:
    - role: roles/compute.networkAdmin
      members:
        -  serviceAccount:{{ include "opsman.fullname" . }}-pks-master@{{ .Values.projectID }}.iam.gserviceaccount.com
    - role: roles/compute.instanceAdmin
      members:
        -  serviceAccount:{{ include "opsman.fullname" . }}-pks-master@{{ .Values.projectID }}.iam.gserviceaccount.com
    - role: roles/compute.storageAdmin
      members:
        -  serviceAccount:{{ include "opsman.fullname" . }}-pks-master@{{ .Values.projectID }}.iam.gserviceaccount.com
    - role: roles/roles/compute.securityAdmin
      members:
        -  serviceAccount:{{ include "opsman.fullname" . }}-pks-master@{{ .Values.projectID }}.iam.gserviceaccount.com
    - role: roles/iam.serviceAccountActor
      members:
        -  serviceAccount:{{ include "opsman.fullname" . }}-pks-master@{{ .Values.projectID }}.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1alpha1
kind: IAMPolicy
metadata:
  name: "{{ include "opsman.fullname" . }}-pks-worker"
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1alpha1
    kind: IAMServiceAccount
    name: "{{ include "opsman.fullname" . }}-pks-worker"
  bindings:
    - role: roles/compute.viewer
      members:
        -  serviceAccount:{{ include "opsman.fullname" . }}-pks-master@{{ .Values.projectID }}.iam.gserviceaccount.com
{{- end }}