{{- if .Values.iam.create }}
# above is to disable doing IAM for now until I figure out the bug
# until then IAM is created via README.
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: "{{ include "opsman.fullname" . }}-pks-master"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  displayName: {{ include "opsman.fullname" . }} master acount
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: "{{ include "opsman.fullname" . }}-pks-worker"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  displayName: {{ include "opsman.fullname" . }} worker acount
{{- $dot := . -}}
{{- range .Values.iam.masterRoles }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ include "opsman.fullname" $dot }}-pks-master-{{ . | lower | replace "roles/" "" | replace "." "-" }}
spec:
  member: serviceAccount:{{ include "opsman.fullname" $dot }}-pks-master@{{ $dot.Values.projectID }}.iam.gserviceaccount.com
  role: {{ . }}
  resourceRef:
    kind: Project
{{- end }}
{{- range .Values.iam.workerRoles }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: {{ include "opsman.fullname" $dot }}-pks-worker-{{ . | lower | replace "roles/" "" | replace "." "-" }}
spec:
  member: serviceAccount:{{ include "opsman.fullname" $dot }}-pks-worker@{{ $dot.Values.projectID }}.iam.gserviceaccount.com
  role: {{ . }}
  resourceRef:
    kind: Project
{{- end }}
{{- end }}
