apiVersion: "compute.google.golang.org/v1"
kind: "Instance"
metadata:
  name: "{{ include "opsman.fullname" . }}"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  zone: {{ .Values.instance.zone }}
  name: "{{ include "opsman.fullname" . }}"
  description: "opsman ({{ .Values.version }}) for running pks"
  # can be full URL or just the machineType, if latter will expand it out using project id and zone.
  #machineType: https://www.googleapis.com/compute/v1/projects/<gcp-project-id>/zones/us-central1-a/machineTypes/custom-2-4096
  machineType: {{ .Values.instance.machineType }}
  tags:
    items: ["allow-ssh", "allow-https", "opsman"]
  disks:
    - type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        diskName: {{ include "opsman.fullname" . }}-root
        diskType: zones/us-central1-a/diskTypes/pd-ssd
        diskSizeGb: "150"
        # currently needs to be full URL
        sourceImage: "global/images/{{ include "opsman.fullname" . }}-{{ .Values.version | replace "." "-" }}"
  networkInterfaces:
      # can be full URL or just the network name, if latter will expand it out using project id assuming a global network.
      # - network: https://www.googleapis.com/compute/v1/projects/debian-cloud/global/networks/default
    - subnetwork: regions/us-central1/subnetworks/{{ include "opsman.fullname" . }}-pks-infrastructure
      networkIP: 192.168.101.5
      accessConfigs:
        - name: external-nat
