apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeNetwork
metadata:
  name: {{ include "opsman.fullname" . }}-pks-network
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  description: network for PKS install
  routingMode: REGIONAL
---
apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeSubnetwork
metadata:
  name: {{ include "opsman.fullname" . }}-pks-infrastructure
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  description: infrastructure
  #gatewayAddress: 192.168.101.1
  ipCidrRange: 192.168.101.0/26
  networkRef:
    name: {{ include "opsman.fullname" . }}-pks-network
  region: us-central1
---
apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeSubnetwork
metadata:
  name: {{ include "opsman.fullname" . }}-pks-subnet
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  description: pks
  #gatewayAddress: 192.168.16.1
  ipCidrRange: 192.168.16.0/26
  networkRef:
    name: {{ include "opsman.fullname" . }}-pks-network
  region: us-central1
---
apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeSubnetwork
metadata:
  name: {{ include "opsman.fullname" . }}-pks-services
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  description: services
  #gatewayAddress: 192.168.20.1
  ipCidrRange: 192.168.20.0/22
  networkRef:
    name: {{ include "opsman.fullname" . }}-pks-network
  region: us-central1
