apiVersion: "compute.google.golang.org/v1"
kind: "TargetPool"
metadata:
  name: "{{ include "opsman.fullname" . }}-pks-api"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  name: {{ include "opsman.fullname" . }}-pks-api
  region: us-central1
  instances: []
---
apiVersion: "compute.google.golang.org/v1"
kind: "ForwardingRule"
metadata:
  name: "{{ include "opsman.fullname" . }}-pks-api"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  name: {{ include "opsman.fullname" . }}-pks-api
  IPAddress: https://www.googleapis.com/compute/v1/projects/pgtm-pczarkowski/regions/us-central1/addresses/{{ include "opsman.fullname" . }}-pks-api
  IPProtocol: TCP
  portRange: "8443"
  region: us-central1
  target: https://www.googleapis.com/compute/v1/projects/pgtm-pczarkowski/regions/us-central1/targetPools/{{ include "opsman.fullname" . }}-pks-api
---
apiVersion: "compute.google.golang.org/v1"
kind: "ForwardingRule"
metadata:
  name: "{{ include "opsman.fullname" . }}-pks-uaac"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  name: pks-uaac
  IPAddress: https://www.googleapis.com/compute/v1/projects/{{ .Values.projectID }}/regions/us-central1/addresses/{{ include "opsman.fullname" . }}-pks-api
  IPProtocol: TCP
  portRange: "9021"
  region: us-central1
  target: https://www.googleapis.com/compute/v1/projects/{{ .Values.projectID }}/regions/us-central1/targetPools/{{ include "opsman.fullname" . }}-pks-api
---
apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeFirewall
metadata:
  name: "{{ include "opsman.fullname" . }}-pks-api"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  description: allow pks api
  allow:
    - protocol: tcp
      ports: ["8443","9021"]
  networkRef:
    name: {{ include "opsman.fullname" . }}-pks-network
  targetTags: ["{{ include "opsman.fullname" . }}-pks-api"]
  sourceRanges: ["0.0.0.0/0"]