# Default values for opsman.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

version: 2.6.8-build.192
storageBucket: ops-manager-us

instance:
  zone: us-central1-a
  machineType: zones/us-central1-a/machineTypes/n1-standard-2

database:
  password: a-bad-opsman-password
  host: "%"

dns:
  # don't put a `.` at the end.
  createZone: false
  zone: example.com

iam:
  create: false
  masterRoles:
    - roles/compute.networkAdmin
    - roles/compute.instanceAdmin
    - roles/compute.storageAdmin
    - roles/compute.securityAdmin
    - roles/iam.serviceAccountActor
  workerRoles:
    - roles/compute.viewer

opsmanAddress:
pksAddress:
projectID: google-project-id

certManagerEmail: paul@here.com

google:
  region: us-central1
  zones: [us-central1-a, us-central1-b, us-central1-c]

pks:
  plans:
    addons: ""

database:
  enabled: false
  host: "%"
  password:
