apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: firewalls.compute.google.golang.org
spec:
  group: compute.google.golang.org
  names:
    kind: Firewall
    listKind: FirewallList
    plural: firewalls
    singular: firewall
  scope: Namespaced
  version: v1
