apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: addresses.compute.google.golang.org
spec:
  group: compute.google.golang.org
  names:
    kind: Address
    listKind: AddressList
    plural: addresses
    singular: address
  scope: Namespaced
  version: v1
