apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gcc.fullname" . }}
  labels:
{{ include "gcc.labels" . | indent 4 }}
    control-plane: controller-manager
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
{{ include "gcc.labels" . | indent 6 }}
      control-plane: controller-manager
      controller-tools.k8s.io: "1.0"
  serviceName: cnrm-controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
        controller-tools.k8s.io: "1.0"
{{ include "gcc.labels" . | indent 8 }}
    spec:
      containers:
      - args:
        - --stderrthreshold=INFO
        command:
        - /root/manager
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 60Mi
          requests:
            cpu: 100m
            memory: 40Mi
        volumeMounts:
        - mountPath: /var/secrets/google
          name: gcp-service-account
      terminationGracePeriodSeconds: 10
      volumes:
      - name: gcp-service-account
        secret:
          secretName: {{ .Values.secretName }}