apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeFirewall
metadata:
  name: "{{ include "opsman.fullname" . }}-allow-https"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  description: allow https traffic
  allow:
    - protocol: tcp
      ports: ["443"]
  networkRef:
    name: {{ include "opsman.fullname" . }}-pks-network
  sourceRanges: ["0.0.0.0/0"]
  targetTags: ["allow-https"]
---
apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeFirewall
metadata:
  name: "{{ include "opsman.fullname" . }}-allow-ssh"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  description: allow ssh traffic
  allow:
    - protocol: tcp
      ports: ["22"]
  networkRef:
    name: {{ include "opsman.fullname" . }}-pks-network
  sourceRanges: ["0.0.0.0/0"]
  targetTags: ["allow-ssh"]
---
apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeFirewall
metadata:
  name: "{{ include "opsman.fullname" . }}-allow-http"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  description: allow ssh traffic
  allow:
    - protocol: tcp
      ports: ["80"]
  networkRef:
    name: {{ include "opsman.fullname" . }}-pks-network
  sourceRanges: ["0.0.0.0/0"]
  targetTags: ["allow-http"]
---
apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeFirewall
metadata:
  name: "{{ include "opsman.fullname" . }}-all"
  labels:
    app.kubernetes.io/name: {{ include "opsman.name" . }}
    helm.sh/chart: {{ include "opsman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  description: allow internal
  allow:
    - protocol: tcp
    - protocol: udp
    - protocol: icmp
  networkRef:
    name: {{ include "opsman.fullname" . }}-pks-network
  targetTags: ["pkslab","opsman"]
  sourceTags: ["pkslab","opsman"]