kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcp-cloud-compute-operator
subjects:
- kind: ServiceAccount
  name: gcp-cloud-compute-operator
  namespace: cnrm-system
roleRef:
  kind: ClusterRole
  name: gcp-cloud-compute-operator
  apiGroup: rbac.authorization.k8s.io
