apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: configure-opsman-cert
spec:
  steps:
    - name: configure-opsman-cert
      image: paulczar/om
      env:
        - name: OM_TARGET
          valueFrom:
              configMapKeyRef:
                name: opsman-auth
                key: host
        - name: OM_USERNAME
          valueFrom:
              configMapKeyRef:
                name: opsman-auth
                key: user
        - name: OM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: opsman-auth
              key: password
        - name: CERT_PEM
          valueFrom:
            secretKeyRef:
              name: opsman-cert
              key: tls.crt
        - name: KEY_PEM
          valueFrom:
            secretKeyRef:
              name: opsman-cert
              key: tls.key
      command:
        - om
      args:
        - --skip-ssl-validation
        - update-ssl-certificate
        - "--certificate-pem=$(CERT_PEM)"
        - "--private-key-pem=$(KEY_PEM)"
